# Generated by Django 4.1 on 2022-08-10 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={
                "permissions": [("take_survey", "Может пройти опрос")],
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.AddField(
            model_name="poll",
            name="users",
            field=models.ManyToManyField(
                related_name="polls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи",
            ),
        ),
    ]
